---
- name: GoReplay | Install
  import_tasks: install.yml
  tags:
    - install
    - goreplay_install

- name: GoReplay | Configure
  import_tasks: configure.yml
  tags:
    - configure
    - goreplay_configure

- name: GoReplay | Service
  import_tasks: service.yml
  tags:
    - service
    - goreplay_service
